### ISSUE TITLE
Error trying to apply GCP Provider

### ISSUE THREAD

**Issue by rbizzell40** [PacktPublishing/End-to-End-Automation-with-Kubernetes-and-Crossplane#1]
I am following along in the book End-to-End-Automation with Kubernetes Crossplane and I am hitting an error when trying to apply the GCP Provider.  I am running Kind v0.14 version 1.21.1 on MacOS. The specific error " resource mapping not found for name: "provider-gcp" namespace: "cross-plane" from "gcp-provider.yaml": no matches for kind "Provider" in version"pkg.crossplane.io/v1 ensure CRDs are installed first"

Is there something that needs to be installed first I have the kubectl extension installed already for crossplane and any help would be greatly appreciated.

**Comment by ArunRamakani** [comment]
The error indicates that the crossplane is not running successfully in your cluster. 

Can you share the output of --- kubectl get all -n crossplane-system

Most probably the issue happened because you try to apply the Provider before Crossplane components become alive. You have to wait till the Crossplane components are up and running.

**Comment by rbizzell40** [comment]
I fixed it all good thanks.
